Products/urls.py
from django.urls import re_path, path
from . import views as product_views
urlpatterns = [
    re_path(r'^(?P<category>\w+)/$',view=product_views.ViewCategoryProducts.as_view(),name='all_products'),
    re_path(r'^products/(?P<product_name>\w+)/$', view=product_views.ProductDetailView.as_view(), name='details')    
]

backend/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    re_path(r'admin/', admin.site.urls),
    re_path(r'shopin/', include('shopin.urls')),
    re_path(r'__reload__/', include('django_browser_reload.urls')),
    re_path(r'products/(?P<shop_name>\w+)/', include('Products.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

shopin/urls.py
"""
    Urls patterns specific to shopin app
    These urls are included in the main url confi
"""
from django.urls import re_path
from shopin import views as shopin_views
urlpatterns = [
    re_path(r'^$', shopin_views.ShopView.as_view(), name='shop'),
    re_path(r'^(?P<shop_id>\d+)/$', shopin_views.SingleShopView.as_view(), name='single_shop')
]

Products/models.py
from django.db import models
from shopin.models import Shop
import decimal
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
def upload_product_image(instance, filename):
    """Returns the path to upload the product image to"""
    
    return f"images/products/{instance.name}/{filename}"


class Brand(models.Model):
    brand = models.CharField(max_length=100,
                             verbose_name='brand_name')

    def __str__(self) -> str:
        return ('Brand: %s'%(self.brand))



class Features(models.Model):
    content = models.CharField(max_length=255)
    Specification = models.ForeignKey('Specification',
                                      on_delete=models.CASCADE,
                                      null=True)

    def __str__(self) -> str:
        return ('Features: %s'%(self.Specification))
    


class Specification(models.Model):
    title = models.CharField(max_length = 100)
    product = models.ForeignKey('Product',
                                on_delete=models.CASCADE,
                                null=True)
    def __str__(self) -> str:
        return ('Specification: %s'%self.title)

class AboutProduct(models.Model):
    subject = models.CharField(max_length=100,
                               verbose_name='subject of the product',
                               null=True)
    content = models.TextField(max_length=500,
                               verbose_name='more about the product')
    product = models.ForeignKey('Product', on_delete=models.CASCADE)

    def __str__(self) -> str:
        return (f'{self.subject} -- {self.product}')


class Description(models.Model):
    title = models.CharField(max_length=100,
                             verbose_name='description title' )
    body = models.TextField(max_length=550)
    product = models.ForeignKey('Product',
                                on_delete=models.CASCADE,
                                null=True)

    def __str__(self) -> str:
        return (f'description: {self.title} --related to {self.product}')



class Product(models.Model):
    """Model for a Product object"""

    name = models.CharField(max_length=100, verbose_name="product name")
    shortdescription = models.TextField(max_length=300,
                                        verbose_name="product short " +
                                        "description")
    note = models.TextField(max_length=500,
                            verbose_name='what users should be concerned with',
                            null=True, blank=True)
    # longdescription = models.TextField(max_length=3000,
    #                                    verbose_name="product long description")
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=100,
                              verbose_name='product status',
                              blank=True)
    quantity = models.IntegerField(default=1,
                                   verbose_name='product quantity')
    warrantyears = models.IntegerField(blank=True, default=0)
    warranty_and_support = models.TextField(max_length=550,
                                            null=True,
                                            blank=True)
    created_date = models.DateField(auto_now_add=True)
    issponsored = models.BooleanField(default=False)
    image = ProcessedImageField(upload_to = upload_product_image,
                                processors= [ResizeToFill(300,260)],
                                format='JPEG',
                                options={'quality': 70}, null=True)
    discount_amount = models.DecimalField(max_digits=10,
                                          decimal_places=2,
                                          null=True,
                                          default= 0.00,
                                          verbose_name='amount payable after discount')
    discount_rate = models.PositiveSmallIntegerField(null=True, default=0)
    # if a customer has a coupon, he or she can purchase the product at the discount rate
    # has a relationship with product
    shop = models.ForeignKey(Shop, related_name='shop_products',
                             on_delete=models.CASCADE)
    shopingCart = models.ForeignKey('ShoppingCart',
                                    on_delete=models.CASCADE,
                                    null=True, blank=True)
    order = models.ForeignKey('Order', on_delete=models.CASCADE,
                              null=True, blank=True)
    section = models.ForeignKey('shopin.Section',
                                on_delete=models.CASCADE,
                                null=True, blank=True)
    category = models.ForeignKey("shopin.Category",
                                 on_delete=models.CASCADE,
                                 null=True, blank=True)
    subcategory = models.ForeignKey('shopin.Subcategory',
                                    on_delete=models.CASCADE,
                                    null=True, blank=True)
    brand = models.ForeignKey('Brand',
                              on_delete=models.CASCADE,
                              null=True, blank=True)
    # products will relate to a coupon
    coupon = models.OneToOneField('Coupon',
                                  on_delete=models.CASCADE,
                                  null= True, blank=True)
    related_products = models.ManyToManyField('self',
                                              blank=True,
                                              symmetrical=False)

    def __str__(self) -> str:
        return (f'product - {self.name}-{self.shop.title}')

    @property
    def has_related_products(self):
        if self.related_products.exists:
            return True
        return False
    

    @property
    def compute_discounted_cost(self):
        """Returns the cost of a product after computing the rate of discount on the original cost"""
        convert_rate = decimal.Decimal(self.discount_rate / 100)
        print(convert_rate, end= ' ')
        print(self.cost)
        discount_amount = convert_rate * self.cost
        print(discount_amount)
        amount_payable = round((self.cost - discount_amount), 2)
        print(amount_payable)
        return amount_payable
    
    @property
    def sectionBelongsToShop(self) -> True or ValueError:
        """Checks if a section is associated with this shop"""

        if self.shop.title == self.section.shop.title:
            return True
        else:
            raise ValueError('Section and Shop selected are not related')

    @property
    def sectionAcceptsProductOnly(self) -> bool:
        """Checks if a section accepts only products"""

        return (self.section.contains_products_only)

    @property
    def categoryBelongsToShop(self) -> True or ValueError:
        """Checks if a category a product belongs to
        is associated with this Shop"""

        if self.category.shop.title == self.shop.title:
            return True
        else:
            raise ValueError('category and shop are not related')

    @property
    def subcategoryBelongsToShop(self):
        """Checks if the subcategory selected
        is associated with a shop"""

        if self.subcategory.category.shop.title == self.shop.title:
            return True
        else:
            raise ValueError('SubCategory and Shop selected are not related')

    def save(self, *args, **kwargs):
        """Overrides the save method and saves a product"""

        self.status = 'in-stock'
        if self.quantity == 0:
            self.status = 'out-of-stock'

        if self.discount_amount == 0.00 and self.discount_rate >= 0:
            self.discount_amount = self.compute_discounted_cost

        # before i save i need to know whether
        # or not the section accepts only
        # products and whether or not the section
        # belongs to the given shop
        if self.section:
            if self.sectionBelongsToShop \
                and self.sectionAcceptsProductOnly:
                    super().save(*args, **kwargs)
            else:
                raise ValueError('Section does not accept only products')
        if self.category:
            if self.categoryBelongsToShop:
                super().save(*args, **kwargs)

        if self.subcategory:
            if self.subcategoryBelongsToShop:
                super().save(*args, **kwargs)

        super().save(*args, **kwargs)


class ShoppingCart(models.Model):
    """Models the pushing cart in a real shop"""

    datecreated = models.DateField(auto_now_add=True)
    customer = models.OneToOneField('customers.Customer',
                                    default=None,
                                    on_delete=models.CASCADE,
                                    null=True)

    def __str__(self) -> str:
        return (f"{self.customer.first_name} - shopping Cart")

    # i going to prevent the user from saving a cart which already exists
    @classmethod
    def prevent_double_carts(cls, cart_name):
        """Make sure that we don't have a repeated cart for a user"""

        if cart_name in cls.objects.all():
            raise ValueError(f'{cart_name} already exists')
        return False

    def save(self, *args, **kwargs):
        """Override the save method"""

        cart_save_name = f'{self.customer.first_name} - shopping Cart'
        if not ShoppingCart.prevent_double_carts(cart_name=cart_save_name):
            super().save(*args, **kwargs)


class Order(models.Model):
    """Models an Order Made on Products in an Ecommerce website"""

    customer = models.ForeignKey('customers.Customer',
                                 default=None,
                                 on_delete=models.CASCADE,
                                 null=True)

    def __str__(self) -> str:
        return (f'{self.customer.first_name} - Order')
    

Products/views.py
from django.shortcuts import render
from django.views import View
from .models import Product
from shopin.models import Shop, Category
# Create your views here.

class ViewCategoryProducts(View):
    def get(self, request, shop_name, category):
        # get all products related to a particular shop
        try:
            # do a test
            requested_category = Category.objects.get(name=category)
            if requested_category.shop.title == shop_name:
                products = requested_category.product_set.all()
        except Shop.DoesNotExist:
            pass
        
        for product in products:
            if product.discount_rate:
                print('hear')
        # Products = [{
        #     "image":'image1',
        #     'sponsored': True,
        #     'description': "GNMN Bluetooth Headphones Wireless Earbuds 48hrs Playback IPX7 Waterproof Ear Buds Over-Ear Stereo Bass Earphones with Earhooks Microphone LED Battery Display for Sports/Workout/Gym/Running Black",
        #     "rating":"5 stars",
        #     'discounted_amount': "$23.39",
        #     'price': '$27.99',
        #     'coupon': '20%',
        #     'Delivery': 'Delivery Thu, Aug 17',
        #     'destination': 'Ghana',
        #     'total_rating': '494'

        # },{
        #     "image":'image1',
        #     'sponsored': False,
        #     'description': "Arama USB Headset with Microphone Noise-Cancelling, Comfort Fit Computer Headset with Microphone for PC Laptop Mac Skype Zoom UC Webinar Business Call Center Home Office",
        #     "rating":"5 stars",
        #     'price': '$27.99',
        #     'coupon': '20%',
        #     'Delivery': 'Delivery Thu, Aug 17',
        #     'destination': 'Ghana',
        #     'total_rating': '1,298'
        # }]
        # print products shopping cart
        return render(request, template_name='products/products.html', context={'shop': shop_name,
                                # products in the specific category
                                'products': products})
    
class ProductDetailView(View):
    def get(self, request, shop_name, product_name):
        """Return a Template with the details of a product"""        
        product = Product.objects.get(name = product_name)

        # generate product specification information
        
        return render(request=request, template_name='products/product_details.html',
                      context={'shop': shop_name,
                                'details': product,
                                'thumbnails': [1,2,3,4],
                     })

templates/products/product_details.html
{%extends 'base/base.html'%}

{%block logo%} 
{%if not logo%}<span class=" font-bold text-2xl text-green-500 "> {{shop}} </span>{%endif%}
{%endblock%}
{%block justify%}'justify-center'{%endblock%}
{%block content%}
    <section class="bg-blue-400 flex flex-row space-x-[100px] mx-[20.4em] max-w-[1000px] min-w-[835px] mt-[20px] p-2">
        <div class="bg-slate-300  flex flex-col">
            <div class="bg-slate-600 w-[325px] h-[318px] rounded-lg">image</div>
            <div class="bg-blue-600 flex flex-row space-x-3 p-2 justify-center">
                {%for thumbnail in thumbnails%} 
                    <div class="bg-slate-600 h-[68px] w-[68px] rounded-md">thumbnail</div>
                {%endfor%}
            </div>
        </div>
        <div class="bg-pink-400 p-3 w-[661px]">
            <div class="flex flex-row justify-between">
                <div class="text-orange-300 font-bold"> {{details.shop.title}} SHOP </div>
                <div class="">Rating here</div>
            </div>
            <p class="bg-blue-400"><span class="font-bold text-2xl">{{details.name |title}}</span> <br> 
                <pre class="text-sm">Brand| <span class="">{{details.brand.brand}}</span></pre></p>
            <p class="bg-slate-600 text-white mt-[20px] {%if details.shortdescription|length > 100%} text-sm {%else%}text-md{%endif%}">{{details.shortdescription |title}}</p>
         
            <div class="bg-slate-300 mt-[20px]">
                <!-- This is the discounted amount -->
                <div class="inline-block text-2xl font-bold bg-blue-400">
                    GHC
                    {%if details.discount_rate%} {{details.discount_amount}} {%else%} {{details.cost}}{%endif%}
                </div>
                {%if details.discount_rate%}
                <div class="inline-block bg-orange-100 rounded-md p-1 text-orange-400 text-[18px] ml-[20px] w-[50px] h-[30px] text-center">{{details.discount_rate}}%</div>
                <p class="text-sm text-red-600 line-through font-semibold">Ghc {{details.cost}}</p>
                {%endif%}
            </div>
            
            <div class="mt-10 p-1 flex flex-row justify-center"> 
                <div class="bg-blue-400 h-[50px] rounded-xl inline-block font-bold p-2 text-lg space-x-6">
                    <div class="text-2xl text-orange-300 inline-block cursor-pointer">-</div>
                    <div class="inline-block">0</div>
                    <div class="text-2xl text-orange-300 inline-block cursor-pointer">+</div>
                </div>
                <button class="transition bg-orange-500 hover:opacity-80 h-[50px] w-[14em] ml-[20px] text-white rounded-xl font-bold">Add to cart</button>
            </div>
        </div>
    </section>
    <!-- details and specification section -->
    <section class="bg-blue-400 mt-[20px] grid grid-cols-2 gap-5 mx-[20px]">
        <div >
            <p class="text-center bg-blue-600 text-2xl"> <span class="underline font-semibold">Product Details </span></p>
            {%for content in details.description_set.all%}
                <div class="bg-pink-400">
                    <p class="p-3 font-bold text-lg">{{content.title |title}}</p>
                    <p class="p-3 font-semibold">{{content.body}}</p>
                </div>
            {%endfor%}
        </div>
        <div >      
            <p class="text-center bg-blue-600 text-2xl"><span class="underline font-semibold">Product Specification</span></p>
            <div class="flex flex-col p-14">
                {%for specification in details.specification_set.all%}
                    <div class="bg-slate-200 mb-5">
                        <p class="bg-black-500 font-bold text-white">{{specification.title}}</p>
                        <ul class="list-disc">
                            {%for feature in specification.features_set.all%}
                                <li>{{feature.content}}</li>
                            {%endfor%}
                        </ul>
                    </div>
                {%endfor%}
            </div>
            <div>
                <!-- About the product -->
                <p class="text-center bg-blue-600 text-2xl underline font-bold">About This product</p>
                <div class="p-14 bg-black-500 max-w-[30em]">
                    {%for about in details.aboutproduct_set.all%}
                        <ul class="list-disc">
                            <li><span class="text-orange-300"> {{about.subject}} </span> - <span class="text-slate-400"> {{about.content}}</span></li>
                        </ul>
                    {%endfor%}
                    {%if details.note%} 
                        <p class="mt-3 text-white"><span class="font-bold">note: </span>{{details.note}}</p>
                    {%endif%}
                </div>
            </div>
        </div>
    </section>
    {%if details.has_related_products%}
    <section class="bg-blue-400 mt-[20px] mx-[20px]">
        <!-- this is for the related products -->
        <p class="p-1 font-bold text-2xl">Related Products</p>
        <div class="flex flex-row space-x-2 mt-5 p-2">
            {%for product in details.related_products.all%}
                <div class="bg-black-500 h-fit w-[16em] grid grid-cols-1 rounded-xl transition hover:shadow-xl">
                    <div class="bg-slate-400 h-[9rem] rounded-t-lg">{{product.image}}</div>
                    <div class=" p-3">
                        <p class="text-orange-400 text-sm mt-0">{{product.shortdescription|truncatechars:98}}</p>
                        <p class="text-red-300 mt-1">Rating</p>
                        {%if product.discount_rate%}
                        <div class="text-green-600 inline-block font-bold">Ghc {{product.discount_amount}}</div>
                        <div class="text-green-600 inline-block bg-orange-100 rounded-md font-semibold p-[2px]">{{product.discount_rate}}% <span class="text-sm">discount applied</span><span class="text-red-600 line-through"> Ghc{{product.cost}}</span></div>
                        {%else%}
                            <p class="text-green-600">Ghc {{product.cost}}</p>                            
                        {%endif%}
                        {%if product.coupon%}
                        <div class="mt-[5px]">
                            <span class="bg-green-300 p-[3px]">Save {{product.coupon.coupon_rate}}%</span><span class="text-white"> with</span><span class="text-red-300 font-semibold"> {{product.coupon.title}}</span>
                        </div>
                        {%endif%}
                    </div>
                </div>
            {%endfor%}
        </div>
    </section>
    {%endif%}

{%endblock%}

templates/products/products.html
{%extends "base/base.html"%}
{%load static%}
{%block logo%} <span class=" font-bold text-2xl text-green-500">{{shop}} </span> {%endblock%}
{%block content%} 
<section class="flex flex-row lg:mx-3 space-x-2">
    <nav class="bg-slate-400 lg:basis-1/4 flex-auto ">Hello</nav>
    <main class="bg-slate-400 lg:basis-[74em] xl:basis-[70em] flex-auto p-5">
        <p class="mt-0 font-bold text-2xl bg-red-200">Results</p>
        <!-- product section -->
        <section class="mt-3">
            {%for product in products%}

                <div class="bg-slate-600 p-3 mb-3 h-[17em] flex flex-row space-x-2">
                    <div class="bg-pink-200 min-w-[260px] max-w-[300px]">
                        <img src="{{product.image.url}}" alt="product">
                    </div>
                    <div class="bg-white basis-[49em] p-2 flex flex-col">
                        <div class="bg-blue-400">
                            {%if product.issponsored%}
                                <p class="m-0 text-sm text-blue-600">Sponsored!!</p>
                            {%endif%}
                            <p class="mb-3">{{product.shortdescription}}</p>
                            <p>{{product.rating}}--{{product.total_rating}}</p>
                            <p>{%if product.discount_rate%}
                                    <span class="text-2xl text-green-600">Ghc {{product.discount_amount}}</span> 
                                    <span>Ori price: <span class="line-through text-red-600 bg-orange-100 font-bold">ghc {{product.cost}}</span></span>
                                {%else%}
                                <span class="text-green-500 text-2xl">Ghc {{product.cost}}</span>
                                {%endif%}
                                <br>
                                {%if product.coupon%}
                                    <span class="bg-green-300 p-[3px]">Save {{product.coupon.coupon_rate}}%</span> with <span class="text-red-300 font-semibold"> {{product.coupon.title}}</span>
                                {%endif%}
                            </p>
                            <p class="text-sm">{{product.Delivery}}</p>
                        </div>
                        <div class="flex bg-slate-400 items-end h-[100px]">
                            <div class="inline-block">ships to <span class="text-2xl">{{product.destination}}</span></div>
                            <div class="inline-block ml-[450px]"><button class="transition bg-orange-500 hover:opacity-80 h-[50px] w-[10em] ml-[20px] text-white rounded-xl font-bold flex p-1">
                                 <div class="inline-block"><img src="{%static 'addcart.png'%}" alt="" class="h-12"></div> <div class="inline-block text-xs w-[90px] h-10 p-3">Add to cart</div> 
                            </button>
                        </div> 
                        </div>
                        <p></p>
                    </div>
                </div>
            {%endfor%}
        </section>
    </main>
</section>

{%endblock%}