backend/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    re_path(r'admin/', admin.site.urls),
    re_path(r'shopin/', include('shopin.urls')),
    re_path(r'__reload__/', include('django_browser_reload.urls')),
    re_path(r'products/(?P<shop_name>\w+)/', include('Products.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

shopin/urls.py
"""
    Urls patterns specific to shopin app
    These urls are included in the main url confi
"""
from django.urls import re_path
from shopin import views as shopin_views
urlpatterns = [
    re_path(r'^$', shopin_views.ShopView.as_view(), name='shop'),
    re_path(r'^(?P<shop_id>\d+)/$', shopin_views.SingleShopView.as_view(), name='single_shop')
]

shopin/models.py
"""
    contains my data layer to access
    sqlite database
"""
from django.db import models
from pathlib import Path
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import random
import csv

def upload_image_to(instance, filename):
    saveLocations = {
        'category': 'images/category/%s/%s' % (instance.name, filename),
        'subcategory': 'images/subcategory/%s/%s' % (instance.name, filename),
        'shop': 'images/shop/%s/%s' % (instance.name, filename)
    }
    return (saveLocations.get(instance.__class__.__name__.lower(),
                              f'images/extra/{filename}'))



class Shop(models.Model):
    """
        A Table representing a Shop object
        contains functionalities of a Shop
    """
    PATH_TO_CSV = Path(__file__).resolve().parent.parent
    top_rated = []
    name = models.CharField(max_length=100, default='',
                             verbose_name='SHP_Name')
    email = models.EmailField(null=True)
    contactLine = models.CharField(max_length=20, null=True,
                                   verbose_name='contact')
    description = models.TextField(default='',
                                   verbose_name='SHP_Description',
                                   max_length=270)
    location = models.CharField(max_length=50, default='',
                                verbose_name='SHP_Location')
    rating = models.IntegerField(default=0,
                                 verbose_name='SHP_Rating')
    color = models.CharField(max_length=20, default='black')
    moto = models.CharField(max_length=100,
                            verbose_name='SHP_Moto')
    logo = ProcessedImageField(
        upload_to = upload_image_to,
        processors= [ResizeToFill(300, 300)],
        format= 'JPEG',
        options={'quality': 70},
        null = True
    )

    def __str__(self):
        # return the string representation for each repr
        return self.name + '--' + self.location

    __repr__ = __str__

    @classmethod
    def numberOfShops(cls):
        return (len(cls.objects.all()))
    
    @classmethod
    def instantiate_SHP_from_csv(cls):
        """This method will read from an CSV file and instantiate the obj"""
        with open('%s/modules/ShopTest.csv' % (Shop.PATH_TO_CSV), 'r') as SHP_info:
            reader = csv.DictReader(SHP_info)
            list_of_shop = list(reader)
        for shop in list_of_shop:
            Shop.objects.create(
                title=shop['Title'],
                description=shop['Description'],
                location=shop['Location'],
                rating=int(shop['Rating']),
                color=shop['Color'],
                moto=shop['Moto']
            )
    # create an instance method

    def check_is_top_rated(self):
        """checks whether an instance is top rated"""
        if self.rating == 5:
            return True
        return False

    # randomly generate the three top rated shop
    @classmethod
    def all_top_rated(cls):
        """returns all top rated shop instances"""
        return [
            shop
            for shop in cls.objects.all()
            if shop.check_is_top_rated()
        ]

    @classmethod
    def randomly_fetch_three_top_rated(cls):
        """randomly pick three top rated
           from the all top rated shop
        """
        no_top_rated = 3
        three_random_top_rated_shop = []
        # i will have to make sure that this refreshes after a day is over
        if cls.numberOfShops() < no_top_rated:
            three_random_top_rated_shop.extend(cls.objects.all())
        else:
            for count in range(no_top_rated):
                random_index = random.randint(0, 2)
                three_random_top_rated_shop.append(cls.all_top_rated()[random_index])

        return three_random_top_rated_shop
# have the many relationship


class Section(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    name = models.CharField(max_length=60,
                            verbose_name='section_name', blank=True, null=True)
    # contains_products_only = models.BooleanField(default=False)
    contains_category = models.BooleanField(default=False)
    color = models.CharField(max_length=20)
    pagnation_unit = models.SmallIntegerField()

    def __str__(self) -> str:
        if self.name:
            return (f"section: {self.name} will contain " +
                    f"only products: {self.contains_products_only}")
        return (f"section of:{self.shop.title} will contain " +
                f"only products:{self.contains_products_only}")

    @property
    def contains_products_only(self) -> bool:
        """Checks if a section contains only products"""
        
        return not self.contains_category

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # self.contains_category = self.category.exists()


class Category(models.Model):
    """This repr a category and some functionality that it can contain"""
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    name = models.CharField(max_length=60,
                            verbose_name='Category')
    # read more into working with image field
    image = ProcessedImageField(upload_to = upload_image_to,
                                processors=[ResizeToFill(430,385)],
                                format='JPEG',
                                options={'quality':70}, null=True)
    wants_subcategory = models.BooleanField(default=False)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f'category-{self.name}'

    @property
    def categoryContainsImage(self):
        if not self.wants_subcategory:
            return (True if self.image else False)
        return True

    def save(self, *args, **kwargs):
        if self.section:
            if self.section.shop.title == self.shop.title:
                if self.section.contains_category:
                    # i need to make sure that the category contains images
                    if not self.categoryContainsImage:
                        raise ValueError('Ensure that category contains an image')
                    super().save(*args, **kwargs)
                else:
                    raise ValueError('Section should accept category before it can be saved')
            else:
                raise ValueError('You must select a section inside a shop')
        else:
            super().save(*args, **kwargs)


class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    image = ProcessedImageField(upload_to=upload_image_to,
                                processors=[ResizeToFill(200,140)],
                                format='JPEG',
                                options={'quality':70})

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        if self.category.wants_subcategory:
            super(SubCategory, self).save(*args, **kwargs)
        else:
            raise ValueError("This cateogry does not support subcategories")

templates/shopin/assign.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Assignment</title>
    <link rel="stylesheet" href="./assign.css">
</head>
<body>
    <main>
        <header>
            <div>
                <h1 class="logo"><a href="#">CoDed</a></h1>
                <h2><a href="#">by CoDed_Arch</a></h2>
            </div>
            <div>
                
                <ul class="header-ul">
                    <li class="first"><a href="#">My Blog</a></li>
                    <li><a href="#">My Photos</a></li>
                    <li><a href="#">My Favorites</a></li>
                    <li><a href="#">About Me</a></li>
                    <li><a href="#">Contact Me</a></li>
                </ul>
            </div>
        </header>
        <section class="hero">
            <span class="hero-h">welcome to CoDed!</span><br>
            <span class="below-hero-h">posted on January 11th, 2022 by Author</span>

            <p>Nulla facilisi. <a href="#">Mauris diam justo</a>, pharetra nec, varius viverra, luctus sed, arcu. Aliquam feugiat venenatis metus. In justo dolor, adipiscing a, <a href="#">commodo id</a>, congue sed, est. Suspendisse vel dolor tristique nisl tristique vulputate. <a href="#">Proin blandit risus at leo</a>. Etiam sit amet magna in mi suscipit pharetra.</p>

            <p>Filed under <a href="#" class="category">Uncategorized</a> | <a href="#" class="comment">1 Comment &raquo;</a></p>

            <span class="hero-h">sample tags</span><br>
            <span class="below-hero-h">Posted on January 1st, 2021 by Author</span>

            <p class="dif-p">An unordered list:</p>
            <ul class="list">
            <li><a href="#">Suspendisse quis gravida massa felis.</a></li>
            <li><a href="#">Vivamus sagittis bibendum erat.</a></li>
            <li><a href="#">Nullam et orci in erat viverra ornare.</a></li>
            </ul>

            <p class="dif-p">An ordered list:</p>
            <ol class="list">
            <li><a href="#">Nullam et orci in erat viverra ornare.</a></li>
            <li><a href="#">Suspendisse quis gravida massa felis.</a></li>
            <li><a href="#">Curabitur malesuada turpis nec ante.</a></li>
            </ol>

            <p class="dif-p">A blockquote: </p>
            <blockquote>
            <p>&#8220;Sed eu diam. Vivamus nonummy elit et odio. Fusce risus quam,  scelerisque sed, pharetra ut, pharetra id, ante. Etiam posuere, elit a  blandit varius, velit sem tincidunt elit, et pulvinar pede ligula a  sapien. Donec fermentum condimentum nisi. Proin iaculis mauris id lorem  viverra molestie. Duis vel orci. Nam consequat. Morbi nec lacus. Fusce  egestas sagittis enim.&#8221;</p>
            </blockquote>

            <p>Filed under <a href="#" class="category">Uncategorized</a> | <a href="#" class="comment">1 Comment &raquo;</a></p>
        </section>
        <section class="archives-category">
            <div>
                <p class="titles">archives</p>
                <ul>
                <li><a href="#">January 2022</a></li>
                <li><a href="#">December 2021</a></li>
                <li><a href="#">November 2021</a></li>
                <li><a href="#">October 2021</a></li>
                <li><a href="#">September 2021</a></li>
                <li><a href="#">August 2021</a></li>
                <li><a href="#">July 2021</a></li>
                <li><a href="#">June 2021</a></li>
                <li><a href="#">May 2021</a></li>
                <li><a href="#">April 2021</a></li>
                <li><a href="#">March 2021</a></li>
                <li><a href="#">February 2021</a></li>
                <li><a href="#">January 2021</a></li>
                </ul>
            </div>
            <div>
                <p class="titles">
                    categories
                </p>
                <ul>
                <li><a href="#">Quisque vestibulum</a> (23)</li>
                <li><a href="#">Sed a nisl a lacus</a> (78)</li>
                <li><a href="#">Quisque sagittis</a> (11)</li>
                <li><a href="#">Etiam volutpat</a> (34)</li>
                <li><a href="#">In aliquet hendrerit</a> (65)</li>
                <li><a href="#">Suspendisse iaculis</a> (35)</li>
                <li><a href="#">Nam vel risus at</a> (22)</li>
                <li><a href="#">Praesent sit amet</a> (54)</li>
                </ul>
            </div>
        </section>
    </main>
    <p class="copy-right">Copyright &copy; 2006. Designed by <a href="#"><strong>CoDed_Arch</strong></a></p>
</body>
</html>

templates/shopin/index.html
{% extends 'base/base.html'%}
{%load static%}
{%block advertisement%} 
<!-- <div class="bg-black-400 flex xl:w-[200px]">
j
</div> -->
{%endblock%}

{%block logo%}<span class=" font-bold text-2xl text-green-500"> SHOPIN </span>{%endblock%}
{%block content%}
<div class="flex xl:m-10 flex-wrap justify-left space-y-4 p-4 h-fit">
    {% for shop in top_rated %}
    <!-- change of business logic. This div is to show list of only 5 rated -->
        <div class="bg-black-500 bg-opacity-20 w-[50em] h-[421px] rounded-md p-1">
            <div class="flex flex-row justify-center">
                <!-- logo section -->
                <div class="inline-block w-[15em] ml-[20em]">
                    <img src="{{shop.logo.url}}" alt="shop_logo" class="rounded-[20em] h-[11em]">
                </div>
                <div class="inline-block w-[15em]">
                    <img src="{%static 'medal.png'%}" alt="" class="ml-[12em]">
                </div>
            </div>
            <p class="text-center font-bold text-3xl">{{shop.name |upper}}</p>
            <div class="grid grid-cols-2 gap-x-[13em]"> 
                <div class="h-[3em] flex flex-row p-2 pl-[5em]">
                    <div class="inline-block"><img src="{%static 'phone.png'%}" alt="call" class="w-7"></div>
                    <div class="inline-block p-1 pl-4 font-semibold font-sans">{{shop.contactLine}}</div> 
                </div>
                <div class="h-[3em] flex flex-row p-2">
                    <div class="inline-block"><img src="{%static 'mail.png'%}" alt="call" class="w-7"></div>
                    <div class="inline-block p-1 pl-4 font-semibold font-sans">{{shop.email}}</div>
                </div>
                <div class="h-[3em]">
                    <details>
                        <summary class="font-mono text-xl p-2 pl-[5em]">
                            About Shop
                        </summary>
                        <p class="bg-black-500 bg-opacity-30 font-mono text-xl ml-[5em] w-[20em] rounded-md">{{shop.description}}</p>
                    </details>
                </div>
                <div class="h-[3em] flex flex-row p-2">
                    <div class="inline-block "><img src="{%static 'location.png'%}" alt="call" class="w-7"></div>
                    <div class="inline-block p-1 pl-4 ">{{shop.location}}</div>
                </div>
            </div>
            <div>
                <button class="right ml-[40em] mt-[3em] bg-green-500 h-10 w-[9em] rounded-md flex p-2 font-mono font-semibold pl-6">SHOP NOW <img src="{%static 'rightarrow.png'%}" alt="" class="ml-1 w-6"></button>
            </div>
        </div>
    {% endfor %}
</div>
<div class="bg-black-400 xl:m-10 flex flex-row space-x-4 flex-wrap pt-[20px] pb-[20px] pl-[20px] justify-center">
    {%for all_shops in shop_list %}
    <div class="bg-{{all_shops.Colors}}-400 basis-[15em] h-[15em] rounded-xl flex flex-col ">
        <!-- two divs to repr thumnail and other features -->
        <div class="bg-slate-600 basis-1/2 font-bold">
            Thumnail here
        </div>
        <div class="bg-slate-600 basis-1/2">
            <p class="bg-yellow-200 p-[5px]">{{all_shops.title}}</p>
            <p class="bg-green-300 truncate pl-[5px] font-semibold">{{all_shops.moto|truncatechars:20}}</p>
            <p class="bg-orange-300 truncate text-center font-semibold">{{all_shops.rating}}</p>
            <div class="bg-black-400 p-[10px] flex flex-row justify-center">
                <button class="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300 hover:bg-green-500 h-[30px] w-[100px] font-bold rounded-md bg-white text-green-500 hover:text-black-400 hover:shadow-md hover:shadow-emerald-300">Shop</button>
            </div>
        </div>
    </div>
    {%endfor%}
</div>
{%endblock content%}

templates/shopin/single_shopview.html
{%extends 'base/base.html'%}
{%load static%}
{%load custom_filters%}
{%block content%}
<!--each shop page would have it's individual sections-->
    {%for section in content.section_set.all%}
        {%if section.contains_category%}
        <!-- convert into a flex box -->
            <section class="bg-black-400 mb-10 mx-[12em] justify-center max-w-[1441px] flex flex-row p-[10px] space-x-5">
                {% for category in section.category_set.all|slice:":{{section.pagnation_unit}}"%}
                       <div class="bg-red-400 max-w-[356px] min-w-[356px] h-[421px] xl:px-[5px]">
                            <p class="text-center font-bold"> {{category.name}}</p>
                        {%if category.wants_subcategory%}
                            <div class="grid grid-cols-2 gap-4 bg-black-400 h-[310px]">
                                {%for sub_cat in category.subcategory_set.all|slice:":4"%}
                                    <div class="bg-indigo-400 rounded-md flex flex-col">
                                        <div class="bg-red-400 h-[105px] font-bold">
                                            <!-- render the image here -->
                                            <img src="{{sub_cat.image.url}}" alt="img">
                                        </div>
                                        <div class="bg-yellow-400 h-[40px] pt-3 font-light pl-2">
                                            {{sub_cat.name}}
                                        </div>
                                    </div>
                                {%endfor%}
                            </div>
                        {%else%}
                            <div class="bg-black-400 text-white h-[310px]">
                                <!-- render the images here -->
                                <img src="{{category.image.url}}" alt="">
                            </div>
                        {%endif%}
                            <div class="text-blue-400 xl:mt-[20px]">
                                see more ->
                            </div>
                        </div>
                {%endfor%}
            </section>
            <!-- stopped here with the development -->
        {%elif section.contains_products_only%}
            <section class="bg-black-400 mb-10 mx-[13.5em] p-[10px] flex flex-col">
                <div class="bg-white p-[4px] flex flex-row">
                    <h1 class="font-bold text-2xl">{{section.name}}</h1>
                    <p class="text-blue-600 p-[4px] text-l font-bold">{{section_value.call_to_action}}</p>
                </div>
                {%for item in section_value.products%}
                    <div class="flex flex-row space-x-2">
                        {%if item|is_dict%}
                        <!-- this section contains both thumb nails and product details -->
                            <div class="w-[244px] h-[277px] bg-green-400 flex flex-col">
                                <div class="bg-yellow-400 h-[200px] font-bold">{{item.img}}</div>
                                <div class="bg-inherit h-[77px]">
                                    {%if item.offer%}
                                    <div class="bg-white flex space-x-2">
                                        <p class="bg-red-600 text-white p-[2px]">{{item.offer}}</p> <div class="text-red-600 font-bold text-[13px] py-[4px]">{{item.offer_name}}</div> 
                                    </div>
                                    <p class="font-bold">{{item.price}}</p>
                                    <p class="truncate">{{item.desc}}</p>
                                    {%endif%}
                                </div>
                            </div>
                        {%else%}
                    </div>
                    <!-- yes so this section just contains only the thumbnails -->
                        <div class="w-[244px] h-[203px] bg-green-400">
                            {{item}}
                        </div>
                    {%endif%}
                {%endfor%}
            </section>
        {%endif%}
    {%endfor%}
{%endblock content%}